export const SliderData = [
    {
        image: "./images/Let's go out and play!.jpg",
        title: "Let's go out and play!",
        medium: "Digital drawing, Procreate. 2022",
        description: "Looking past the walls of mortality into unknown infinite beauty.",
    },
    {
        image: "./images/The Leap.jpeg",
        title: "The Leap",
        medium: "Digital drawing, Procreate. 2022",
        description: "Sometimes to get to where you want to go, you have to take a leap.",
    },
    {
        image: "./images/Khailbut.png",
        title: "Khailbut",
        medium: "Digital drawing, Procreate. 2022",
        description: "Every culture has stories of the shadow people. The Ancient Egyptians referred to them as the khailbut and believe they were one of our seven souls. They believed that the shadow was always present, even after death. In The Egyptian Book of the Dead, the deceased was often depicted as a shadow, or silhouette, with little descriptive features. It was not evil unless the deceased was evil in life.",
    },
    {
        image: "./images/Life_Mocked.jpg",
        title: "Welcome to the Headroom",
        medium: "Digital drawing, Procreate. 2022",
        description: "As the billionaires guide us into the Metaverse, Max Headroom has been there, waiting for us since 1985.",
    },
    {
        image: "./images/The Great Chicago Ring of Fire.jpg",
        title: "The Great Chicago Ring of Fire",
        medium: "Digital drawing, Procreate. 2022",
        description: "In 2021, Chicago experienced one of its most violent and crime riddled years in recorded history. In response to this failure of leadership, I created this portrait of Chicago Mayor Lori Lightfoot.",
    },
    {
        image: "./images/War. Horses of the Apocalypse 1 - 4.png",
        title: "War",
        medium: "Digital drawing, Procreate. 2022",
        description: "The fiery horse of war has rides into town.",
    },
    {
        image: "./images/Death. Horses of the Apocalypse- 4 - 4.png",
        title: "Death",
        medium: "Digital drawing, Procreate. 2022",
        description: "Death. The last chapter of any true story. The red horse named War is all that remains. He lies dead in a dead world, a world he killed.",
    },
    {
        image: "./images/Down in the Valley Below.jpeg",
        title: "Down in the Valley",
        medium: 'Pencil, marker, gold paint, collage. 9" X 15", 2021',
        description: "I approach dark and heavy subjects with bright colors and a light heart.",
    },
    {
        image: "./images/for-dad.jpeg",
        title: "For Vern. I love you dad.",
        medium: 'Pen, ink, colored pencil, collage. 36" X 36", 2021',
        description: "In 2020, I lost my father. The following year, I made this piece for my mother for Valentines day.",
    },
    {
        image: "./images/Fred the Gnome.jpeg",
        title: "Fred the Gnome",
        medium: 'Pencil on paper. 6" X 9", 2021',
        description: "Fred is grumpy... Every time it snows, everyone thinks he's an elf. He wants people to know that there is a big difference!",
    },
    {
        image: "./images/tree-of-light.jpeg",
        title: "Tree of Light",
        medium: 'Ink, oil pastel on MDF panel. 24" X 12" 2017',
        description: "Live in light.",
    },
    {
        image: "./images/triptych.png",
        title: "A Picture of Good Health",
        medium: 'Pencil, ink, oil stick, cedar paper, gold leaf, collage. 3: 12" X 36", 2012',
        description: "A visual exploration of mindfulness.",
    },
    {
        image: "./images/triptych-1-3.jpeg",
        title: "Mind",
        medium: 'Pencil, ink, oil stick, cedar paper, gold leaf, collage. 12" X 36", 2012',
        description: "",
    },
    {
        image: "./images/triptych-2-3.jpeg",
        title: "Body",
        medium: 'Pencil, ink, oil stick, cedar paper, gold leaf, collage. 12" X 36", 2012',
        description: "",
    },
    {
        image: "./images/triptych-3-3.jpeg",
        title: "Soul",
        medium: 'Pencil, ink, oil stick, cedar paper, gold leaf, collage. 12" X 36", 2012',
        description: "",
    },
    {
        image: "./images/love.jpeg",
        title: "Love Thy Neighbor",
        medium: "Acrylic paint, garage door. 16' X 7', 2020",
        description: "Chicago saw an explosion of crime at the onset of the Covid-19 pandemic. I painted this mural on my garage to try and spread love in my neighborhood.",
    },
    {
        image: "./images/namaste.jpeg",
        title: "Namaste",
        medium: 'Oil pastel on paper, 12" X 9", 2002',
        description: "Eyes closed self portrait.",
    },
    {
        image: "./images/espolon.jpeg",
        title: "Ramon the Rooster",
        medium: 'Acrylic on canvas, 48" X 24", 2014',
        description: "Inspired by Steven Nobles illustrations, this piece tells the story of Guadalupe and Rosarita joining Father Miguel Hidalgo in his brave campaign for Mexican independence from Spain. The duo fought fiercely with undying passion. As Ramón the Rooster crowed his shrill battle cry, the brave army of revolutionists clashed against tyranny, against the cruel caste system, willing to sacrifice everything for the cause. This movement set the stage for Mexicos eventual independence."
    
    },
    {
        image: "./images/wedding.PNG",
        title: "Fiesta de Amor",
        medium: "Digital painting, Freshpaint, 2014",
        description: "My first digital painting. Done for our wedding thank you cards.",
    },
    {
        image: "./images/figure-2.jpeg",
        title: "Reclining Figure",
        medium: 'Compressed charcoal on paper, 18" X 24", 2001',
        description: "",
    },
    {
        image: "./images/energy-embrace.jpeg",
        title: "Energy Embrace",
        medium: 'Charcoal on paper, 22" X 24", ',
        description: "Bask in the glow of the dammed flow. (Interior of the Hoover Dam)",
    },
    {
        image: "./images/city-breathes.jpeg",
        title: "The City Screams",
        medium: 'Gesso, charcoal, graphite on paper, 24" X 24", 2002',
        description: "Inspired by the work of Max Ernst and the technique of decalcomania.",
    },
    {
        image: "./images/robo-v-skelly.JPG",
        title: "Robot Vs. Skelly",
        medium: 'Monoprint, 15" X 12" 2001',
        description: "Every since I was a little kid, I have always loved drawing robots and skeletons. Here's an old one I came across.",
    },
    {
        image: "./images/The Witch.jpeg",
        title: "The Witch",
        medium: "Digital drawing, Procreate, 2022",
        description: "Part of an upcoming series on superstitions and their origins. Many modern superstitions date back to the medieval times and the fear of witchcraft. This piece is based off of SALIGIA art common in the 1400's.",
    },
    {
        image: "./images/The Witch's Cat.jpeg",
        title: "The Witch's Cat",
        medium: "Digital drawing, Procreate, 2022",
        description: "Part of an upcoming series on superstitions and their origins. Many modern superstitions date back to the medieval times and the fear of witchcraft. During this time, single women who kept cats as pets were often persecuted as witches.",
    },
]